import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Rochester } from "next/font/google";
import { GlobalProvider } from "@/components/global-context";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/components/theme-provider"; // ✅ Correct Named Import

const rochester = Rochester({
  variable: "--font-rochester",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const allCookies = cookieStore.getAll();
  const cookieString = allCookies.map(
    (cookie) => `${cookie.name}=${cookie.value}`
  ).join("; ");

  const res = await fetch(`${process.env.HOST}/api/users/me`, {
    method: "GET",
    headers: {
      Cookie: cookieString,
    },
  });
  const data = await res.json();

  return (
    <html lang="en">
      <body className={`${rochester.variable} antialiased`}>
        <ThemeProvider> {/* ✅ This should now work correctly */}
          <GlobalProvider initEmployee={data.employee}>{children}</GlobalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}